//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForksnSpoons.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Article { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> MaxDiscount { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Distributor Distributor { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual OrderList OrderList { get; set; }
    }
}
